  CONTAINER_REL_PATH:
    container_name: CONTAINER_NAME
    build: containers/CONTAINER_REL_PATH/.
    volumes:
      - ./volume:/notebooks/volume
      - ./containers/CONTAINER_REL_PATH/src/.jupyter:/opt/conda/envs/fastai/etc/jupyter
    environment:
      - DATABASE_URL=
    ports:
        - 8889:8888