  CONTAINER_REL_PATH:
    container_name: CONTAINER_NAME
    build: containers/CONTAINER_REL_PATH/.
    volumes:
      - ./sharedfolder:/notebooks
      - ./containers/CONTAINER_REL_PATH/src/.jupyter:/opt/conda/envs/fastai/etc/jupyter
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/propertymgr_daily_snapshot
    ports:
        - 8889:8888